# Generated by Django 4.2.7 on 2024-03-01 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abon',
            name='pay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abn', to='app.payment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 1, 17, 48, 0, 184943, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
