# Generated by Django 4.2.7 on 2024-03-07 07:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_abon_pay_alter_user_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeraides',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='answers_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerconseil',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='answers_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qan',
            name='price',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='typefic',
            name='format_of',
            field=models.CharField(default='fiche', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 7, 44, 45, 739573, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
