# Generated by Django 4.2.7 on 2024-03-07 21:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answeraides_views_answerconseil_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('aide', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='app.aides')),
                ('conseil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='app.conseils')),
            ],
        ),
        migrations.RemoveField(
            model_name='answeraides',
            name='views',
        ),
        migrations.RemoveField(
            model_name='answerconseil',
            name='views',
        ),
        migrations.AlterField(
            model_name='qan',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typefic',
            name='format_of',
            field=models.CharField(default='fichiers', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 21, 7, 50, 984335, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.AddField(
            model_name='staffwork',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL),
        ),
    ]
