# Generated by Django 4.2.7 on 2024-03-07 23:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staffwork_remove_answeraides_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeraides',
            name='views',
            field=models.ManyToManyField(related_name='answers_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerconseil',
            name='views',
            field=models.ManyToManyField(related_name='answers_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 23, 22, 47, 26944, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
